### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by WJBeBetter** [MMF-FE/vue-svgicon#1]
请问一下现在实现的svg只有dome上的那些吗

**Comment by Allenice** [comment]
你好，这个工具已经在我们项目中使用，你问的这个问题我有点不太理解，这是一个生成 svg icon 组件的工具，不是一个组件图标库。

**Comment by WJBeBetter** [comment]
好吧- - ，没见过类似的 还以为是组件图标库

**Comment by WJBeBetter** [comment]
请问一下 关于import 'icon/vue' 提示我没有装载该模块   是需要另外装载吗？

**Comment by WJBeBetter** [comment]
- - 我找到了  不好意思 添麻烦了

**Comment by WJBeBetter** [comment]
用起来好酷！！！好评！！
