### ISSUE TITLE
SVGs with multiple paths all get the "fill" color

### ISSUE THREAD

**Issue by bbusch19** [MMF-FE/vue-svgicon#100]
As stated above, when using the color prop, if you have an SVG that contains multiple paths, each path gets the fill color. This results in the SVG being rendered as a solid square. 

```html
<svg version="1.1" viewBox="0 0 24 24" class="svg-icon svg-fill" data-v-4f1ab3a5="">
    <path fill="red" stroke="none" pid="0" d="M7.41 15.41L12 10.83l4.59 4.58L18 14l-6-6-6 6z">. 
    </path>
    <path fill="red" stroke="none" pid="1" d="M0 0h24v24H0z" _fill="none"></path>
</svg>
```

**Comment by Allenice** [comment]
This is because I anticipate that most icons will be a single color. If there is a single color icon with multiple paths, I only need one color for the color property.
