### ISSUE TITLE
Default width/height

### ISSUE THREAD

**Issue by Mattyon** [MMF-FE/vue-svgicon#102]
Hi,

I have multiple icons that has various widths/heights. In your examples (and even after implementing it) you require `width` and `height` to be set (otherwise it doesn't show anything).

That's pretty dumb since we can't really rely on static widths/heights.

Is there a way how to access the height/width from the original SVG file, or to use defaults? I can see that it registers itself with those properties.

Thanks

**Comment by Allenice** [comment]
You can use `scale` prop

**Comment by Mattyon** [comment]
Thanks, that will solve my use-case. I wanted to avoid modifying the template.
