### ISSUE TITLE
docs and eslint issue

### ISSUE THREAD

**Issue by grount** [MMF-FE/vue-svgicon#109]
The documentation states that in order to use svg-icon library we should do the following:
`npm install vue-svgicon --save-dev`
and use like this:
```
import SvgIcon from 'vue-svgicon'

// Default tag name is 'svgicon'
Vue.use(SvgIcon, {
    tagName: 'svgicon'
})
```

using this example results in eslint error:
`ESLint: 'vue-svgicon' should be listed in the project's dependencies, not devDependencies (no import/no-extraneous-dependencies)`

Is the only workaround is to disable eslint for the next line?
with:
`// eslint-disable-next-line import/no-extraneous-dependencies`

**Comment by Allenice** [comment]
You can use [Custom icon content format](https://github.com/MMF-FE/vue-svgicon#custom-icon-content-format).
