### ISSUE TITLE
After Build process I don't see any svg

### ISSUE THREAD

**Issue by albertodeago** [MMF-FE/vue-svgicon#11]
While trying in development with webpack-dev-server everything is great!
After the compilation (made with webpack, with a conf similiard to the default created with vue-cli) instead I see no svg, my guess is an import issue but I really don't know. 
src tree:
- assets
  - svg-origin (folder with the real svgs to "compile")
  - svg (output of the compilation made with vue-svgicon)
  - various pngs....
- components
- helpers

the build folder is as follows:
- target/
  - ce/
    - manager/
      - build.js
      - assets/
         - various pngs...

Am I missing something?

**Comment by albertodeago** [comment]
I get that svg's files should not be found in the assets folders, but when I run the application from the generated build.js I have no svg where it should be rendered, I got an element like this: 
<svgicon icon="arrow-up" width="50" height="50"></svgicon>
Thus nothing is displayed

**Comment by Allenice** [comment]
@albertodeago If there is no problem running in the development mode, then the production model should also be no problem. I think you should check the configuration of the build production model

**Comment by albertodeago** [comment]
Do I need to configure differently my loaders? I don't get why they are not there.

from webpack.config
module: {
      rules: [
        {
          test: /\.vue$/,
          loader: 'vue-loader',
          options: {
            loaders: {
              'scss': 'vue-style-loader!css-loader!sass-loader',
              'sass': 'vue-style-loader!css-loader!sass-loader?indentedSyntax'
            }
          }
        },
        {
          test: /\.css$/,
          loader: 'style-loader!css-loader'
        },
        {
          test: /\.js$/,
          loader: 'babel-loader',
          exclude: /node_modules/
        },
        {
          test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
          loader: 'url-loader',
          options: {
            limit: 10000
          }
        },
        {
          test: /\.(png|jpg|gif|svg)$/,
          loader: 'file-loader',
          options: {
            name: './assets/[name].[ext]?[hash]'
          },
        }
      ]
    },
    resolve: {
      alias: {
        'vue$': 'vue/dist/vue.esm.js'
      }
    }

**Comment by albertodeago** [comment]
Jesus christ, was a super distraction error of mine, everythings works great! Thanks

Just to umiliate myself I'll explain the problem, I have two entry points (one for prod and one for dev) and in the prod one I forgot to write the ''Vue.use(svgicon)" line. Strangely enough (and this is why I scratched my head a lot to find this) is that I had no error or warning error whatsoever.
