### ISSUE TITLE
Index files for subfolders

### ISSUE THREAD

**Issue by Kuzzy** [MMF-FE/vue-svgicon#14]
Hello, first of all, I want to say that this plugin did the job well.

But I want to suggest one small improvement. In big projects with hundreds of icons, it doesn't make much sense to import all icons at once, because bundle will become huge. But it is also too complicated to import icons one by one... Wouldn't it be much easier to generate an index.js file for each subfolder and not include root index.js files from subfolders? In this case, it would be much easier to manage imports of icons and icons groups:

```javascript
// Import icons from root directory only, without subfolders. This import may be done in root app component or layout.
import 'icons'

// Import all icons from subfolder to import in a specific component.
import 'icons/my-component1'
```
Does it make sense?

I'm not very familiar with node.js, but I've pushed some quick workaround into [fork](https://github.com/Kuzzy/vue-svgicon/commit/b524449d58a2a113a30d9e7b2150c695e71f15d9), can you please take a look? What do you think, can be something similar implemented?

**Comment by Allenice** [comment]
@Kuzzy fixed! [v1.2.1](https://github.com/MMF-FE/vue-svgicon/releases/tag/v1.2.1)
