### ISSUE TITLE
Icon are not visible in firefox

### ISSUE THREAD

**Issue by fortael** [MMF-FE/vue-svgicon#16]
I have a svg-logo before icon that i need. The problem is that i don't see the icon at all, it's just invisible. 
`fill` property not work. I have very strange behavior and this is how problem could be solved:
- I can delete svg icon of logo, then i see
- I can set same `clip-path` property.

So that mean `clip-path` works wrong here? And i'm here because i cannot do anything with `clip-path` in this plugin.

**Comment by Allenice** [comment]
Can you post an example here? @fortael

**Comment by fortael** [comment]
https://jsfiddle.net/u0t4tupu/4/
Here. Please try in latest firefox. 

You can try remove first svg or change `clip-path="url(#svgicon-a)"` to `clip-path="url(#svgicon-h)"` on second one.

**Comment by fortael** [comment]
https://stackoverflow.com/questions/45394418/why-i-cannot-use-some-svg-in-firefox/45402455#45402455

**Comment by Allenice** [comment]
@fortael fixed! [v1.2.2](https://github.com/MMF-FE/vue-svgicon/releases/tag/v1.2.2)
