### ISSUE TITLE
Disabling eslint on generated .js files

### ISSUE THREAD

**Issue by gtso86** [MMF-FE/vue-svgicon#18]
Could you write `/* eslint-disable */` at the top of every genereated file to avoid tons of eslint warnings?

**Comment by Allenice** [comment]
It is good to add `/* eslint-disable */` by default.  I will add it in next version.  Now you can use **icon template** to custom the format of your generated icons

**Comment by gtso86** [comment]
Thanks for the idea! But I still have some eslint warning because the index.js don't add ';' on the end of the required files.

I'm using eslint-config-airbnb rules and they're really stricted.

**Comment by Allenice** [comment]
@gtso86 You can config your eslint to ignore the icons directory
