### ISSUE TITLE
SVG Sprite

### ISSUE THREAD

**Issue by Redani** [MMF-FE/vue-svgicon#19]
Hi thanks for your work.
Is it possible to generate an external svg sprite with your script?

Thanks

**Comment by Allenice** [comment]
Why you need SVG sprite when you can use inline SVG?

**Comment by Redani** [comment]
Thanks @Allenice for your reply.
Well, I'd like to use an external sprite to prevent having a lot of inline code...

**Comment by Allenice** [comment]
@Redani Sorry, I think I can't add this feature.  Inline SVG will not make  server requests, it is build into your main js file.

**Comment by benoitemile** [comment]
Hi there, up on this, it would be really useful to be able to sprite them, i'm having a 250k+ bytes of inline svgs on category page.
Spriting could lead to faster first paint and being able to cache sprite.svg file.
