### ISSUE TITLE
primary module does not work on the server

### ISSUE THREAD

**Issue by corsen2000** [MMF-FE/vue-svgicon#2]
[The primary module](https://github.com/MMF-FE/vue-svgicon/blob/master/dist/index.js) referred to by **main** will not run on the server due to its reference to `document`.

I am building a universal application using Nuxt.js and this caused problems for us.

I am able to work around this by using an `alias` to re-point `vue-svgicon` [at the source itself](https://github.com/MMF-FE/vue-svgicon/blob/master/component/svgicon.vue), which does not have any references to `document`.

This code seems perfectly capable of running in both environments. Looking at the build for this project I am not able to understand why webpack is adding references to `document` at all. I'm not sure what feature it is trying to provide for the library by doing so.

Please let me know if I can help further.

**Comment by Allenice** [comment]
Why there has **document** because it will insert some css style to dom.  Use the source can work because the css style is managed in your build system.

**Comment by vfasky** [comment]
try jsdom , [example](https://github.com/MMF-FE/vue-svgicon/blob/master/test/setup/setup.js)

**Comment by corsen2000** [comment]
Thanks for the explanation of why that code is being generated. For now, I think I will keep my override and use the `.vue` file directly. Nuxt.js seems to be able to do the right thing on the server and the client with this configuration.

It seems unfortunately that I have to do anything special to use this project with Nuxt.js, but I am new to the Vue.js scene and I have no ideas on how it can be improved if possible at all.

Please feel free to close this issue if there is nothing else to do at this time. For now, this code is working in my project well.

**Comment by Allenice** [comment]
Think you for your issue. I have no server side rendering experience， so I don't in consideration of it when I setup this project. I will try to find a way to make server-side and client-side easy to use.

**Comment by Ca4tkin** [comment]
@corsen2000 , could you explain in detail how to make it work with Nuxt? Which alias should be changed?

**Comment by corsen2000** [comment]
@Ca4tkin `config.resolve.alias['vue-svgicon$'] = 'vue-svgicon/component/svgicon.vue';` is what I am using in `extend(config)`.
