### ISSUE TITLE
Options for default values

### ISSUE THREAD

**Issue by tornography** [MMF-FE/vue-svgicon#20]
Currently the values for height and width are set to 16 pixels.
But most of the times icons are used corresponding with text, so they are used to be set to 1em.

Right now one has to pass height/width to each and every component.
Would't it be possible to set additional option in `Vue.use('svgicon', {})`?

Regards,
Manuel

**Comment by Allenice** [comment]
@tornography Add in [v1.2.4](https://github.com/MMF-FE/vue-svgicon/releases/tag/v1.2.4)
