### ISSUE TITLE
Preserve original icon color

### ISSUE THREAD

**Issue by talski** [MMF-FE/vue-svgicon#29]
Hello, when I run this script on a colored svg, the colors are lost, so for some icons like the one below, it would be painful to write each color, there's a way to keep the color when converting?
 
![groceries](https://user-images.githubusercontent.com/740549/30603560-e403e396-9d35-11e7-8182-aaf454c86ac6.png)

**Comment by gensmann** [comment]
Another area this would be useful is flag icons.

**Comment by Allenice** [comment]
Add in v2.1.0
