### ISSUE TITLE
SSR. Doesn't work => icon.register() is not a function

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [MMF-FE/vue-svgicon#30]
Hello and thank you for simplifying workflow with svg icons.

## Story
I have read the #2, so I have tried the use of adding an alias to already existing ones:
```
'vue-svgicon$': 'vue-svgicon/component/svgicon.vue'
```
I am using the latest vue.js, webpack, and other deps.
Basically, I am using almost identical boilerplate to [vue-hackernews](https://github.com/vuejs/vue-hackernews-2.0).

## Problem
I have checked my SVGs without SSR, they work fine.
However with SSR, it then produces an error:
```
icon.register is not a function
```
Please let me know any ideas on what might be an issue.

**Comment by Allenice** [comment]
Please update to v2.0.0 and try again, and you should read `README` for v2.0.0 changes

**Comment by SergeyKhval** [comment]
@Allenice FYI the section with instructions was removed from README in recent commits

**Comment by Allenice** [comment]
@SergeyKhval Yes, It was removed, because you don't need to do anything to deal with SSR.
