### ISSUE TITLE
click change pito

### ISSUE THREAD

**Issue by nlefebvre1410** [MMF-FE/vue-svgicon#39]
hi,
when I open a window or click it sometimes happens that the svg turns into a square do you know why?
![capture d ecran 2017-12-11 a 15 30 31](https://user-images.githubusercontent.com/3309884/33836051-a0265ef8-de88-11e7-890d-6577f3105a32.png)

Thank you in advance for your assistance

**Comment by Allenice** [comment]
Can you show me an example or your svg file?

**Comment by nlefebvre1410** [comment]
hi,

`   <template slot="action" slot-scope="props">
                <span @click="onClidRow(props.row)" class="curser"><svgicon name="icon-arrow-down" width="10" height="10"
                                                             color="#0375d8 #3891e0"></svgicon></span>
                <a class="download curser" :href="onDownload(props.row)" download="proposed_file_name"
                   @click="onDowClick(props.row)">
                    <svgicon name="icon-download" width="14" height="14" color="#0375d8 #3891e0"></svgicon>
                </a>
            </template>`

**Comment by nlefebvre1410** [comment]
@Allenice hi ,
the solution ?

**Comment by Allenice** [comment]
Sorry, I can't do anything for this issue.
