### ISSUE TITLE
Wrong order of 'width' and 'height' in 'viewBox'

### ISSUE THREAD

**Issue by paulinekorkina** [MMF-FE/vue-svgicon#42]
This is what generating in icon.js:

icon.register({
  'icon': {
    width: 20,
    height: 24,
    viewBox: '0, 0, 24, 20',
    data: `... some data ...`
  }
})

Looks like viewBox should be '0, 0, 20, 24', so my svg is smaller than I expected.

**Comment by Allenice** [comment]
HI, Can you show me your SVG file?
