### ISSUE TITLE
svg not displayed: iconData null

### ISSUE THREAD

**Issue by plweil** [MMF-FE/vue-svgicon#45]
The icons are not being displayed. Using this script, I've got the compiled svgs in src/compiled-icons:

     "generate-icons": "vsvg -s ./svg-icons -t ./src/compiled-icons"

When viewed in DevTools, the svg-icon component's iconData computed property is null, which suggests that it doesn't know where the icons are. Do I have to explicitly import each individual icon (or the entire icon directory)?

**Comment by Allenice** [comment]
You should import generated icons. Please view: https://github.com/MMF-FE/vue-svgicon#use-generated-icon
