### ISSUE TITLE
Problem in production

### ISSUE THREAD

**Issue by carmas123** [MMF-FE/vue-svgicon#46]
Hi, I've a big problem with your lib. I use it correctlly in development but when I build it for production the icons are lost. I see the svg tag into my page but nothing into it.
The path of svg was lost.

Please can you help me please?
I use webpack to build my production files.

**Comment by carmas123** [comment]
All work fine when I open the first time the page, but if I refresh the page (es. with F5) this problem occur.

**Comment by Allenice** [comment]
Can you give me a demo?

**Comment by carmas123** [comment]
Oh no I'm sorry but this a big project.
Please can you tell me what I need to check in Webpack config?

**Comment by carmas123** [comment]
Solved... thank you so much

**Comment by bmw27** [comment]
@carmas123 I'm having the same problem where the icons show in development but not in production. Do you remember how you fixed it?

**Comment by bmw27** [comment]
@carmas123 Never mind, I figured it out! I was using PurgeCSS to remove unused CSS classes, and it was removing some SVG classes I needed. I whitelisted any class with "svg" in the name so PurgeCSS doesn't delete it.
