### ISSUE TITLE
Cannot make it work with typescript

### ISSUE THREAD

**Issue by ErikMalmqvist** [MMF-FE/vue-svgicon#47]
I´m getting the following error when trying to use vue-svgicon in a vue.js 2.x project with typescript.

"message": "Could not find a declaration file for module 'vue-svgicon'. 'xxx/node_modules/vue-svgicon/dist/index.js' implicitly has an 'any' type.\n  Try `npm install @types/vue-svgicon` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-svgicon';`",

**Comment by Allenice** [comment]
You can exclude node_modules fold in tsconfig.json or your webpack loader config
