### ISSUE TITLE
vsvg generate doesn't work but deletes output directory

### ISSUE THREAD

**Issue by Helmi** [MMF-FE/vue-svgicon#48]
I'm trying to get this to work with nuxt but it seems like I'm failing early. I put one svg file in the source directory and executed `vsvg -s ./svg -t ./assets/svg` – unfortunately everything that happens is that the directory specified through -t gets deleted. I thought it may be needing bash to run and I was using fish shell but then exited fish and started bash just to see the same behaviour.

What am I missing?

This is for version 2.1.3

**Comment by Allenice** [comment]
It seems that your source directory is empty or wrong. When exec command, it will delete previous icons and create new one.

**Comment by Helmi** [comment]
Are there any special requirements for the svg files to work with the script? I'm quite sure I didn't have the source directory wrong - I even tried different directory namings, different svg files. Weird. I'm going to retry.

**Comment by Helmi** [comment]
Looks like I've really just done something wrong. Maybe shouldn't have tried this after 16 hours of coding. Sorry for the silly issue. Closing it.
