### ISSUE TITLE
SVG images get filled with black color

### ISSUE THREAD

**Issue by waghcwb** [MMF-FE/vue-svgicon#49]
Sometimes (I don't know the reason for that) my SVG icons get filled with black color. This happens because the plugin is renaming the `fill` attribute to `_fill`

![image](https://user-images.githubusercontent.com/6169950/41170985-347e00c8-6b25-11e8-812e-3770e96fea69.png)

**Comment by waghcwb** [comment]
Thank you. Solved with this:
```xml
<icon name="loading" :original="true"/>
```

Also, can I set this prop as a default behavior for all icons? Or, I'll need to set it manually in all icons?

**Comment by Allenice** [comment]
@waghcwb Sorry,  You can't.

**Comment by waghcwb** [comment]
Ok, thank you!
