### ISSUE TITLE
vsvg commandline silently fails when using absolute paths.

### ISSUE THREAD

**Issue by jvanveen** [MMF-FE/vue-svgicon#60]
Hello. Thank you for vue-svgicon. Really enjoy having svg icons in my Vue project!
I noticed something that may be an issue, namely if I use the vsvg commandline together with absolute paths, it seems to fail without notice. This works:

`vsvg -s ./build/__tmp/bologna/svg -t ./src/brand/bologna/icons
Generated icon: arrow
Generated icon: availability
Generated icon: check
Generated icon: close
...
`

While this doesn't:
`vsvg -s /home/myuser/projects/vialer-js/build/__tmp/bologna/svg -t /home/myuser/projects/vialer-js/src/brand/bologna/icons`

I would expect the same build output.

**Comment by Allenice** [comment]
Fixed in v3.1.0
