### ISSUE TITLE
If height or width is not set it will default to empty string ""

### ISSUE THREAD

**Issue by sebmor** [MMF-FE/vue-svgicon#62]
Which causes warnings and weird renderings in browsers.

![screen shot 2018-08-16 at 15 06 43](https://user-images.githubusercontent.com/405407/44210158-06588200-a166-11e8-81b4-ed547429b8cc.png)

It would be better to not declare width when the property is missing or set the default css value "auto".

**Comment by Allenice** [comment]
fix in v3.1.0
