### ISSUE TITLE
SVG icon polyfill breaks on ie11???

### ISSUE THREAD

**Issue by Sidstumple** [MMF-FE/vue-svgicon#64]
For a big project we implemented `vue-svgicon`. Since `innerHTML` doesn't work on IE11 and we used the SVG icon polyfill provided in this package. 

You can imagine our surprise when we found out that the polyfill actually breaks everything on IE11. Have you tested this polyfill thoroughly?

**Comment by Allenice** [comment]
I have not tested this polyfill in `v3`.   It's fixed in v3.2.0. 🙏
