### ISSUE TITLE
Alternative suggestion: Naming syntax of subfolder icons

### ISSUE THREAD

**Issue by sebmor** [MMF-FE/vue-svgicon#65]
If you have an icon in a subfolder, for example icons/social/twitter.svg it will be parsed to 
icons/social/twitter.js, and it will register its name as **social/twitter**
```
import icon from 'vue-svgicon'
icon.register({
  'social/twitter': {
    width: 16,
    height: 16,
    viewBox: '0 0 50 50',
    data: '<path pid="0" d="M45 13.2c-1.5.6-3.1 1.1-4.7 1.3 1.7-1 3-2.6 3.6-4.5-1.6.9-3.3 1.6-5.2 2-1.5-1.6-3.6-2.6-6-2.6-4.5 0-8.2 3.7-8.2 8.2 0 .6.1 1.3.2 1.9-6.8-.3-12.9-3.6-16.9-8.5-.7 1.2-1.1 2.6-1.1 4.1 0 2.8 1.4 5.3 3.6 6.8-1.3 0-2.6-.4-3.7-1v.1c0 4 2.8 7.3 6.6 8-.7.2-1.4.3-2.2.3-.5 0-1-.1-1.5-.2 1 3.2 4.1 5.6 7.7 5.7-2.8 2.2-6.3 3.5-10.2 3.5-.7 0-1.3 0-2-.1 3.6 2.3 7.9 3.7 12.6 3.7 15.1 0 23.3-12.4 23.3-23.2v-1.1c1.6-1.4 3-2.8 4.1-4.4z"/>'
  }
})
```

This makes it really hard to import the icons on case by case basis. I have a vue app and I only import the icons I need per component.

```
import { back, chat } from '~/components/icons'
```

but I of course can't do  

```
import { social/twitter } from '~/components/icons/social'
```

I would suggest a syntax change to for example **social_twitter**

**Comment by dschewchenko** [comment]
If you are using nuxt, you can to try https://github.com/dschewchenko/nuxt-svgicon

**Comment by sebmor** [comment]
@dschewchenko looks cool!
vue-svgicon should consider adding your extended config additions to their core :)
