### ISSUE TITLE
Can vsvg be run during webpack build?

### ISSUE THREAD

**Issue by rightaway** [MMF-FE/vue-svgicon#68]
Could the vsvg command that is run manually now be set up to automatically run on each build? Would this be a supported feature or something that could be added? That way I could drop any new svg files into my icons directory, and webpack would automatically take care of it and I could use the vue-svgicon tag in my vue components immediately.

**Comment by rightaway** [comment]
Especially useful for development mode using webpack-dev-server, the workflow isn't ideal right now as I'd like these icon files to be handled the same as all other development assets and JS files during production, rather than them needing to exist somewhere on the filesystem versus everything  else not needing that.

**Comment by rightaway** [comment]
Would you consider adding a webpack loader at some point for this?

**Comment by rightaway** [comment]
If it's added then this package wouldn't need to handle `svgo`, because if it's part of a standard webpack build then we could just use the svgo-loader with the loader for vue-svgicon to take care of that.

**Comment by Allenice** [comment]
The next major version is add this feature, please try it and feedback. https://github.com/MMF-FE/vue-svgicon/tree/dev

**Comment by rightaway** [comment]
Any documentation for how to use the new feature? Didn't see anything in the readme.

**Comment by Allenice** [comment]
> Any documentation for how to use the new feature? Didn't see anything in the readme.

https://github.com/MMF-FE/vue-svgicon/tree/dev
