### ISSUE TITLE
ie11 support

### ISSUE THREAD

**Issue by mahlm** [MMF-FE/vue-svgicon#7]
Seems that svgs won't render in ie11.  The svg element is empty if inspected.

![svg](https://cloud.githubusercontent.com/assets/9116716/25069273/e8bcc232-2241-11e7-9207-71ab8b2dc0c4.JPG)

![empty](https://cloud.githubusercontent.com/assets/9116716/25069281/3b5de6ec-2242-11e7-9c2b-a14dbf68b790.JPG)

**Comment by mahlm** [comment]
After dicking around, found out ie11 doesn't support .innerHTML on svg elements.  [This](https://github.com/dnozay/innersvg-polyfill) is the first google hit polyfill.  Including that, then modify svgicon.vue:

1) remove v-html directive from template svg element
`<svg version="1.1" :class="clazz" :viewBox="box" ref="svg" :style="style"></svg>`

2) inject path on mount
```
mounted () {
      this.$refs.svg.innerHTML = '\n' + this.path
}
```

There are definitely more elegant solutions that involve more thought/work, but this will do for me at the moment.  Hope this helps!

**Comment by mahlm** [comment]
another option that doesn't require a polyfill is to wrap around the svg.

template:
```
<div v-html="svgString" :class="clazz" :style="style">
</div>
```
computed property:
```
      svgString () {
        let styleString = ''
        for (let property in this.style) 
          styleString += `${ property }: ${ this.style[property] }; `
        return `<svg version="1.1" viewBox="${ this.box }" style="${ styleString }"> ${ this.path } </svg>`
      }
```

**Comment by tomByrer** [comment]
Good work with your investigation @mahlm !
I hope only the README is updated to warn a polyfill is needed for IE11 support.  Many using Vue do not need any IE support (mobile, Electron).  IE11 has only 3.4% global usage, so baking in IE11 support is unneeded IMHO.

**Comment by Allenice** [comment]
I will try to fix it when I get a windows machine. @mahlm

**Comment by Allenice** [comment]
@tomByrer I think we should support IE, because It has many user in my country.

**Comment by brianjorden** [comment]
Personally not interested in any extra bloat from polyfills if it added much of anything, I don't even allow logins from older browsers. Totally understand the broader use case for many others though, possibly an opt-in or opt-out feature?

As for IE testing, Microsoft has actually made some official virtual machine images for that exact purpose. Should be free and no signup even needed. Make note of the images expiring though, they suggest just setting a snapshot to roll back.

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by Allenice** [comment]
README file is updated. Use  https://github.com/dnozay/innersvg-polyfill to make IE work.

**Comment by Allenice** [comment]
v1.2.0: https://github.com/MMF-FE/vue-svgicon#work-on-ie-and-old-browser
