### ISSUE TITLE
Original color default value

### ISSUE THREAD

**Issue by ppsirius** [MMF-FE/vue-svgicon#72]
I see default value for width and height it's any chance to do the same with other props? It's anoiyng to type  :original="true" in each icon

**Comment by Allenice** [comment]
Because there is no such feature before. If the default value is true, the `color` property will not work properly.

**Comment by Allenice** [comment]
you can type `original` only

**Comment by ppsirius** [comment]
It's any plan for default value feature in the future?

**Comment by Allenice** [comment]
May provide a plugin option in the next major release.
