### ISSUE TITLE
Getting type error with Vue 2.5.18+

### ISSUE THREAD

**Issue by Eterion** [MMF-FE/vue-svgicon#79]
Hi, I'm getting this type error when using with Vue 2.5.18 or higher (2.5.17 works fine).
The svg icon in html is displayed correctly, so this seems to be just typings error.

![image](https://user-images.githubusercontent.com/7584981/50767180-1ccdba00-127c-11e9-8bac-ddfef3fde25f.png)

![image](https://user-images.githubusercontent.com/7584981/50767276-88178c00-127c-11e9-9de1-d1d4bc8d63e7.png)

OS: Windows
Node: 11.6.0

**Comment by Eterion** [comment]
I've restructured my entire project, and the type error disappeared. I have no idea how it was "fixed"

**Comment by Eterion** [comment]
If anyone is interested, I have encountered this problem again after updating vue dependencies. But this time I figured out how to "fix" it: uninstall all vue dependencies (including vue-svgicon), then install them again, vue-svgicon install as last.

**Comment by Allenice** [comment]
The problem is that the vue dependency of your project and the vue dependency of vue-svgicon are not in the same node_modules, that is, different vue files are referenced.
