### ISSUE TITLE
Add newline to <icon>.js

### ISSUE THREAD

**Issue by ivictbor** [MMF-FE/vue-svgicon#8]
First of all thanks for great work!
It would be nice to add newline to each `js` file with icon, to prevent eslint error http://eslint.org/docs/rules/eol-last (for those who use it), 
for example, add `\n` here will fix the issue:
https://github.com/MMF-FE/vue-svgicon/blob/master/bin/svg.js#L130

**Comment by Allenice** [comment]
Fixed. Now you can use a template file to format the generated icons
