### ISSUE TITLE
Icon not correctly converted

### ISSUE THREAD

**Issue by tiga05** [MMF-FE/vue-svgicon#80]
I try to use an svg icon with the following path infos:

`M144,100v36h-40v-24H88v24H48v-36l48-20L144,100z M132,75V60h-16v8.333L96,60   L48,80v12l48-20l48,20V80L132,75z`

After conversion, the following code is generated:

`<g class="IC-home-48x48"><path pid="0" class="custom-background" d="M0 0h192v192H0z"/><path pid="1" class="custom-fill" d="M96 72L60 87.737V120h28v-16h16v16h28V87.737z"/></g>`

As you can see: The second (M132) and third (L48) info is missing. I tried to "convert" them manually. M132 is working, but I cant get L48 to work.

The fixed M132 looks like this:
`<g class="IC-home-48x48"><path pid="0" class="custom-background" d="M0 0h192v192H0z"/><path pid="1" class="custom-fill" d="M96 72L60 87.737V120h28v-16h16v16h28V87.737z"/><path pid="2" class="custom-fill" d="M132 75V60h-16v8.60"/></g>`

What am I doing wrong? Is this a bug? Can you fix it?

**Comment by Allenice** [comment]
Vue-svgicon uses svgo to optimize SVG content. If the default svgo configuration does not meet your requirements, you can generate a SVG icon with a custom configuration. Read: https://github.com/MMF-FE/vue-svgicon#custom-svgo
