### ISSUE TITLE
The icon appears, but the console has the following error

### ISSUE THREAD

**Issue by lucky1231** [MMF-FE/vue-svgicon#81]
![image](https://user-images.githubusercontent.com/34091424/53778379-75959800-3f37-11e9-9159-50f00b49617d.png)

**Comment by Allenice** [comment]
How you register vue-svgicon?

**Comment by lucky1231** [comment]
> 你如何注册vue-svgicon？

找到原因了，是项目本身引得图标报的错，谢谢你了

**Comment by lucky1231** [comment]
> How you register vue-svgicon?

Find out the reason. It's the project itself that caused the error of the icon. Thank you.
