### ISSUE TITLE
vsvg: command not found

### ISSUE THREAD

**Issue by f3yisayo** [MMF-FE/vue-svgicon#82]
I've spent hours trying to get this to work but nothing seems to be working when I try installing this package from npm both locally and globally.

It does look like the latest version doesn't have the "bin" command set in its package.json on npm which consequentially makes bash not find the command. 

I've tried installing other packages and they work fine without the error, so I don't think my npm config/path is broken.

**Comment by f3yisayo** [comment]
For now, installing version 3.2.0 works with:

`npm install vue-svgicon@3.2.0`

This had the "bin" command set in its package.json

**Comment by Allenice** [comment]
Fix in 3.2.3
