### ISSUE TITLE
Using with Material icons: obliterates fill setting that Material icons relies on

### ISSUE THREAD

**Issue by callumflack** [MMF-FE/vue-svgicon#90]
Material icons rely on aligning the icon artwork within whitespace using an empty path, like this:

```html
<path fill="none" d="M0 0h24v24H0z"/>
```

However, this library adds an underscore to all fills when it compiles a folder of icons: any `fill` becomes `_fill`. Which means that every Material icon appears in the DOM as a box filled with the `currentColor`. 

This is _not_ a game-breaker. A quick find/replace works just fine (which is better than manually setting an array of colours per icon). 

Just wondering if there's a way to avoid underscoring `fill` on every compilation?

**Comment by Allenice** [comment]
You can use `original` prop to use default colors. If you want to use original colors, you can use `isOriginalDefault` plugin option. 

refs:  
- https://github.com/MMF-FE/vue-svgicon#isoriginaldefault
- https://github.com/MMF-FE/vue-svgicon#original

**Comment by callumflack** [comment]
Thanks, this solved my problem.
