### ISSUE TITLE
Option for don't rewrite icon.js if exist

### ISSUE THREAD

**Issue by Smekalin** [MMF-FE/vue-svgicon#91]
Hi! Has ```vsvg``` option for save built js files if I don't want replace it? 

For example:  
I have svg file and run ```vsvg -s ./static/svg/icons -t src/components/icons```. I get built icon.js file and edit it. If I run ```vsvg``` old icon.js will be replaced.

Why I need it:

Mys  icon.js has attributess `_stroke="#D8222A" _fill="#D8222A"` and default color not working. I need edit it to ```stroke="#D8222A" fill="#D8222A"``` - without underline

UPD:
I wrote custom svgo config but svgo have not option for save just ```fill``` not ```_fill```

**Comment by Allenice** [comment]
You can use `original` prop to use default colors. If you want to use original colors, you can use `isOriginalDefault` plugin option. 

refs:  
- https://github.com/MMF-FE/vue-svgicon#isoriginaldefault
- https://github.com/MMF-FE/vue-svgicon#original

**Comment by Smekalin** [comment]
@Allenice Thank you! This is what I was looking for! 

If I want to redefine `fill` color I can write `color="_ black _ black _"`, but what should I do if I want to redefine `stroke`?

**Comment by Smekalin** [comment]
All problems is solved. I close this issue. Thanks!
