### ISSUE TITLE
Default width and height | @next

### ISSUE THREAD

**Issue by artur-laptev** [MMF-FE/vue-svgicon#92]
Hello, please add the default width and height from svg file. Now it's render without height and width attributes but in svg file i have this attributes

**Comment by Allenice** [comment]
The default css style has a height and width of 16px.
```js
import 'vue-svgicon/dist/svgicon.css'
```
ref: 
https://github.com/MMF-FE/vue-svgicon/tree/dev#register-vue-svgicon-plugin

You can set default width and height use plugin options
```js
Vue.use(VueSvgIcon, {
    tagName: 'icon',
    defaultWidth: '1em',
    defaultHeight: '1em'
})
```

ref: https://github.com/MMF-FE/vue-svgicon/tree/dev#defaultwidth--defaultheight

**Comment by artur-laptev** [comment]
i know this things, but i have in every svg width and height as attribute, so it's bad if i will set width and height in every vue component

**Comment by Allenice** [comment]
Use `scale` prop can help?
```html
<icon scale="1" />
```

**Comment by artur-laptev** [comment]
yeap, it works!
Thanks ))
